### ISSUE TITLE
Supporting 6.1 API

### ISSUE THREAD

**Issue by brndnmtthws** [bluejekyll/foundationdb-rs#124]
FDB 6.1.8 is the current stable release, and the 6.1 API has some backward incompatible changes. Here are the details on the changes:

* https://github.com/apple/foundationdb/pull/942
* https://forums.foundationdb.org/t/upcoming-c-api-changes-planned-for-version-6-1/1058

I took a stab at making a PR to support the `610` API version, but it will require either a) breaking backward compatibility or b) wrapping code with `#[cfg(feature = "fdb-6_1")]` blocks all over the place.

Since it's a bit messy, I figured I'd start a discussion first before moving forward. What do people think the best way to move forward is? My preference is to prevent breaking backward compatibility at the expense of introducing some more complexity.

In the meantime, I have a small patch here that uses the `600` API version with the 6.1.x client libraries: https://github.com/brndnmtthws/foundationdb-rs/commit/ee95ad4f1efc1a6050a3f3f8e9974612b545e2b5

**Comment by bluejekyll** [comment]
If it's simple enough to do, the `#[cfg(feature = "fdb-6_1")]` would be the best option for backward compatibility, though we probably want to make it forward compatible, so that anything after 6_1 gets the changes as well. Then the `fdb-6_1` feature would depend on `post-fdb-6_1` feature (as would all future fdb versions...)

There might be some elegant ways of doing this with traits and feature gated modules for those implementations?
